check error code

diff --git a/.github/workflows/sanity_check.yml b/.github/workflows/sanity_check.yml
--- a/.github/workflows/sanity_check.yml
+++ b/.github/workflows/sanity_check.yml
@@ -64,3 +64,7 @@ jobs:
       - name: Build PDF
         run: |
           cd build && make all
+          if [ $? -ne 0 ]; then
+            echo "PDF build failed."
+            exit 1
+          fi
